import { Item, Order } from "@/constants/Types";

export default function FetchAllItems() {
  const data = [
    {
      id: 1,
      code: "A-111",
      name: "Urun123",
      stock: true,
      buying_price: 134.0,
      consignment: 30.0,
      selling_price: 244.0,
      tl_price: 24333.0,
      payment_types: ["Han", "Nejat"],
    },
    {
      id: 2,
      code: "A-222",
      name: "Urun2",
      stock: true,
      buying_price: 123.0,
      consignment: 10.0,
      selling_price: 133.0,
      tl_price: 13333.0,
      payment_types: ["Nejat"],
    },
    {
      id: 3,
      code: "RKL-9052",
      name: "RETOOLS ELEKTRİKLİ 3'LÜ SET (2.28)",
      stock: true,
      buying_price: 150.0,
      consignment: 176.0,
      selling_price: 245.0,
      tl_price: 8500.0,
      payment_types: ["Han", "Kredi Kartı"],
    },
    {
      id: 4,
      code: "RKL-9062",
      name: "RETOOLS 7 Lİ SET PRO MAVİ ( DEKUPAJ + DAL BUDAMA + TESTERE)",
      stock: true,
      buying_price: 98.0,
      consignment: 118.0,
      selling_price: 171.0,
      tl_price: 6250.0,
      payment_types: ["Kredi Kartı"],
    },
    {
      id: 5,
      code: "RKL-9053",
      name: "RETOOLS 3'LÜ SET KAYNAKLI",
      stock: true,
      buying_price: 93.0,
      consignment: 114.0,
      selling_price: 167.0,
      tl_price: 5850.0,
      payment_types: ["Nejat", "Kredi Kartı"],
    },
    {
      id: 6,
      code: "RKL-9059",
      name: "RETOOLS 2'Lİ SET (AKÜLÜ ALICIPAN VIDALAMA + 16 YÖNLÜ KUMANDALI LAZER)",
      stock: true,
      buying_price: 93.0,
      consignment: 114.0,
      selling_price: 167.0,
      tl_price: 5850.0,
      payment_types: ["Han"],
    },
    {
      id: 7,
      code: "RKL-9066",
      name: "RETOOLS 4'LÜ SET KIRMIZI KABARTMALI (3 AKÜ 1 ŞARJ)",
      stock: true,
      buying_price: 107.0,
      consignment: 128.0,
      selling_price: 192.0,
      tl_price: 6950.0,
      payment_types: ["Nejat"],
    },
    {
      id: 8,
      code: "RKL-9068",
      name: "RETOOLS 6'Lİ SET MAVİ (DEKUPAJ-DAİRE TESTERE ÇİFT KUTULU (6 BATARYA 3 ŞARJ)",
      stock: true,
      buying_price: 177.0,
      consignment: 198.0,
      selling_price: 260.0,
      tl_price: 8950.0,
      payment_types: ["Kredi Kartı", "Han"],
    },
    {
      id: 9,
      code: "RKL-9062",
      name: "RETOOLS 5'Lİ SET MAVİ (4'LÜ SET (3 AKÜ 1 ŞARJ) + USB IŞIK)",
      stock: true,
      buying_price: 109.0,
      consignment: 120.0,
      selling_price: 187.0,
      tl_price: 5950.0,
      payment_types: ["Nejat"],
    },
    {
      id: 10,
      code: "RKL-9070",
      name: "RETOOLS 5'Lİ SET MAVİ (4'LÜ SET (3 AKÜ 1 ŞARJ) + 800 NM)",
      stock: true,
      buying_price: 162.0,
      consignment: 180.0,
      selling_price: 241.0,
      tl_price: 8500.0,
      payment_types: ["Han", "Nejat"],
    },
    {
      id: 11,
      code: "RKL-9071",
      name: "RETOOLS 5'Lİ SET MAVİ (4'LÜ SET (3 AKÜ 1 ŞARJ) + 16 YÖNLÜ DİJİTAL GÖSTERGELİ SARI LAZER)",
      stock: true,
      buying_price: 133.0,
      consignment: 155.0,
      selling_price: 224.0,
      tl_price: 7750.0,
      payment_types: ["Kredi Kartı", "Han"],
    },
  ];

  const items: Item[] = data.map((item) => ({
    id: item.id,
    code: item.code,
    name: item.name,
    stock: item.stock,
    buying_price: item.buying_price,
    consignment: item.consignment,
    selling_price: item.selling_price,
    tl_price: item.tl_price,
    payment_types: item.payment_types,
  }));

  return items;
}
